name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust as necessary
      
      - name: Compile Python code
        run: |
          find core -name "*.py" -not -path "core/tests/*" -exec python -m py_compile {} \;

      - name: Run tests
        run: |
          pytest  # Run your tests
